### ISSUE TITLE
API required

### ISSUE THREAD

**Issue by Lonisia** [hlpdev/AdvancedBanX#11]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
AdvancedBanX [3.0.5]

_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
1.8.9

_Please provide the EXACT steps required to reproduce the problem..._
1.
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_
https://pastebin.com/CVKJyaeC

_Add any additional information below._
Your plugin does not work on my server, because we need an advancedbanx or advanced API

**Comment by hlpdev** [comment]
The API is being worked on, I will alert you when it is finished.

**Comment by hlpdev** [comment]
What plugin is trying to get API usage? Please be more specific

**Comment by Lonisia** [comment]
We create our own game plugin using the advancedban API to send webhook sanctions to discord or other uses

**Comment by hlpdev** [comment]
Ok, the API is almost finished and will be available soon. You will have to modify the plugin to work with the AdvancedBanX's API as the package names are different than the original AdvancedBan.

**Comment by hlpdev** [comment]
The API is now available and an explanation on how to add it to your project can be found on the [readme](https://github.com/hlpdev/AdvancedBanX/blob/master/README.md)
