### ISSUE TITLE
AdvancedBanX [3.0.6] ERROR CONSOLE

### ISSUE THREAD

**Issue by Lonisia** [hlpdev/AdvancedBanX#12]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBanX [3.0.6]
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server for the test
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. I add the advancedbanx in the plugins folder
2. I restart the server
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_
https://pastebin.com/ZLN70p6L

_Add any additional information below._

**Comment by hlpdev** [comment]
It seems like you're using an older version of Java based on the error. Please update your Java Runtime.
