### ISSUE TITLE
Little problem

### ISSUE THREAD

**Issue by Lonisia** [hlpdev/AdvancedBanX#2]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBanX 3.0.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 for the test single server
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. I just change a basic message line, by a message in MiniMessage
2. i add this : <red>Click here --></red> <click:open_url:'https://google.com'>ici</click><hover:show_text:'test'></hover>
3. and I did/advancedban reload

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_   
https://pastebin.com/3Ze50kcV

_Add any additional information below._
Send me a discord to give you if need updates to do

**Comment by hlpdev** [comment]
I figured out the issue, I should be able to completely fix any errors that occur when handling MiniMessage formatting by the end of the day. Thanks for bringing this forward!

**Comment by Lonisia** [comment]
Ok thank you! Please also make sure that we can unban a player who has been banned IP through his nickname minecraft and not his IP
