### ISSUE TITLE
 Question about differences

### ISSUE THREAD

**Issue by LadyHaley** [hlpdev/AdvancedBanX#25]
It wasnt clear to me from the plugin page so I though id ask, what are the main differences between this and the original advancedban?
What does this do different or better?

**Comment by hlpdev** [comment]
The main point of this plugin is to be a modernized version of the original AdvancedBan with expanded platform support, bug fixes, and updates. The original developer of AdvancedBan seems to be inactive and the plugin hasn't been updated in around a year. The plugin aims to be a drag and drop replacement against the original plugin for the most part.

Similar to the Essentials fork EssentialsX, AdvancedBanX will continue to receive updates for newer versions of Minecraft, as well as feature updates.
