### ISSUE TITLE
How can i use old color codes "&" or how i cant covert them?

### ISSUE THREAD

**Issue by Raidware** [hlpdev/AdvancedBanX#28]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 3.1.0
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.20.4

_Please provide the EXACT steps required to reproduce the problem..._
1. 
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_
No error

_Add any additional information below._

**Comment by hlpdev** [comment]
Support for legacy color codes are removed in this plugin. Check out [Adventure's MiniMessage formatting](https://docs.advntr.dev/minimessage/format.html). It takes a little getting used to, but it's much better than the legacy formatting. There isn't really a good way of implementing functionality to support both legacy and MiniMessage, so I went with MiniMessage as it provides the most features and ease-of-use options.
