### ISSUE TITLE
How to make clickable text with MiniMessage

### ISSUE THREAD

**Issue by Lonisia** [hlpdev/AdvancedBanX#3]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBanX 3.0.3
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
 single server for the test
_What server version (/version) are you using?_
1.8.9

_Please provide the EXACT steps required to reproduce the problem..._
I can’t make clickable messages with a hovertext with MiniMessage on version 1.8.9 can you give me an example of a clickable text, which makes a redirect on a URL please
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_
Hello <rainbow>world</rainbow>, isn't <blue><u><click:open_url:'https://docs.advntr.dev/minimessage'>MiniMessage</click></u></blue> fun?

_Add any additional information below._
Please also make sure that we can unban a player who has been banned IP through his nickname minecraft and not his IP. And for the command /ban or /tempban made it automatically ban IP as on Litebans

**Comment by hlpdev** [comment]
This is fixed in commit https://github.com/hlpdev/AdvancedBanX/commit/951f2d3ecb44307dd54424d60d2d17306cf9e451
It will be included in version 3.0.4

**Comment by hlpdev** [comment]
3.0.4 has been published in [releases](https://github.com/hlpdev/AdvancedBanX/releases) and on [spigot](https://www.spigotmc.org/resources/advancedbanx.117067/update?update=546715)

**Comment by Lonisia** [comment]
Thank you very much: 3 I await the novelties !
