### ISSUE TITLE
I just want the author to add a sentence in readme.md, "If there is a problem connecting the Mysql database, adjust the version of Mysql to version 5.x"

### ISSUE THREAD

**Issue by TochProud** [hlpdev/AdvancedBanX#34]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 It doesn't matter. This is a problem with the MySQL database and Advancedban does not support the updated verification method.
 
_What kind of server do you have (`Bungeecord/single server`)?_
  It doesn't matter. This is a problem with the MySQL database and Advancedban does not support the updated verification method.
 
_What server version (/version) are you using?_

 It doesn't matter. This is a problem with the MySQL database and Advancedban does not support the updated verification method.

_Please provide the EXACT steps required to reproduce the problem..._
1.nothing
2.nothing
3.nothing

 It doesn't matter. This is a problem with the MySQL database and Advancedban does not support the updated verification method.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_

 It doesn't matter. This is a problem with the MySQL database and Advancedban does not support the updated verification method.

_Add any additional information below._
Add to readme.md：“If there is a problem connecting the Mysql database, adjust the version of Mysql to version 5.x”

**Comment by anmvc** [comment]
A readme fix is basicly saying "fuck you" to server owners who host there server using an hosting provider, instead of throwing a patch onto the issue it should be fixed.
