### ISSUE TITLE
Vulcan Console Commands Not Running 

### ISSUE THREAD

**Issue by ChiefWarPig** [hlpdev/AdvancedBanX#40]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_3.1.0
 
 
_What kind of server do you have (`Bungeecord/single server`)?_Single Server
 
 
_What server version (/version) are you using?_Paper 1.21-111

_Please provide the EXACT steps required to reproduce the problem..._
1.Trigger Vulcan Anti Cheat
2.Vulcan runs console command 'kick %player% &c[Vulcan] Unfair Advantage'
3.Advanced Ban generates an exception in the consol logs 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBanX/logs/latest.log)_
Console Logg: https://pastebin.com/akythMP5

_Add any additional information below._
Unable to provide any logs for /plugins/AdvancedBanX/logs/ as the file is empty

**Comment by hlpdev** [comment]
You must remove the legacy color codes from the kick message. AdvancedBanX uses MiniMessage formatting which you can find [here](https://docs.advntr.dev/minimessage/index.html).
