### ISSUE TITLE
[Enhancement] Ability to select default layout for permanent bans (/ban) and a default for temporary ban (/tempban)

### ISSUE THREAD

**Issue by Ixolaro** [hlpdev/AdvancedBanX#46]
as the title says. 
example: /tempban <username> 30d
and no layout is provided it could use a default layout in config for temporary bans
same for permaban
/ban <username>
and load default layout for permanent bans

**Comment by Ixolaro** [comment]
oh and also add support for ban ID's
example i /ban and in ban message is gives unique ban ID that identifies to the player, like hypixel

**Comment by hlpdev** [comment]
I will look into implementing this. Thank you for the suggestion!
