### ISSUE TITLE
Regarding the fork of "AdvancedBan" as "AdvancedBanX"

### ISSUE THREAD

**Issue by Hopefuls** [hlpdev/AdvancedBanX#49]
Hello hlpdev,

I am one of the supporters and maintainers of AdvancedBan. I do appreciate the decision of you to continue AdvancedBan on your own, rebranding it as "AdvancedBanX". Per the license the repository AdvancedBan uses, this is totally fine to do. 

Though due to possible issues in the future regarding support and branding, I would possibly ask you to do the following (not a legal request or anything, just to avoid confusion within our support):

- Heavily disclose that your fork is not the official AdvancedBan version (it should be noticable). This would be most appreciated on sections that possibly tell users to reach out to support (such as the link to your repository issues and the /advancedban about message).

Best is if this would apply to the following presences of your version:
- GitHub under https://github.com/hlpdev/AdvancedBanX
- SpigotMC (https://www.spigotmc.org/resources/advancedbanx.117067/)
- Modrinth: https://modrinth.com/plugin/advancedbanx/
- Ingame on the Plugin itself
- Any other platforms you intend to publish on in the future 

It should be made clear that support for your plugin should not be sought for on our discord or the original GitHub. This can be done by a larger text for example.

Thank you!

P.S.: Since I've seen some concerns in regards to activity on the project: I can agree, this is mostly due to decisions on implementation and likely the fatigue on maintaining AdvancedBan, though is not "dead" in itself.

**Comment by hlpdev** [comment]
Sorry for causing confusion, I'll make sure to specify that it's a fork, and not an official version on spigot, github, and modrinth.

Thanks for letting me know!
