### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by LKirillK** [hlpdev/AdvancedBanX#61]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 velocity -> single server
 
_What server version (/version) are you using?_
paper 1.21

_Please provide the EXACT steps required to reproduce the problem..._
1. ddos attack (10 minutes)
2. the plugin lost connection to the database on another server (mysql) another ip
3. after the attack, the plugin did not allow players to enter the server
4. logging does not work!!!! I can't attach logs

[16:33:27] [User Authenticator #74/ERROR]: [AdvancedBanX] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBanX/logs/latest.log file and report this error in: https://github.com/hlpdev/AdvancedBanX/issues/new

I think the plugin does not try to reconnect to the database after losing the connection
Also, logs are not working, a file is not being created!!!

**Comment by hlpdev** [comment]
We don't currently have velocity listed as a supported platform.
